---
- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE CEPH STORAGE GENERATED HOSTS"
    block: |
       {% for item in play_hosts %}
       {{ hostvars[item]['ansible_' ~ cluster_storage_interface]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}.stgcluster.bri.co.id
       {{ hostvars[item]['ansible_' ~ public_storage_interface]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}.stgpublic.bri.co.id {{ hostvars[item]['ansible_hostname'] }}
       {% endfor %}
  become: True
  when: create_host_mapping == "yes"

- name: Install and upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
  become: True

- name: Install ca certs
  package:
    name: "{{ item }}"
    state: latest
  become: True
  with_items:
    - ca-certificates
    - apt-transport-https

- block:
    - block:
        - name: Add cloud-archive:ussuri repo
          shell: add-apt-repository cloud-archive:ussuri -y
          become: True

        - name: Install GPG Key of cloud-archive
          apt:
            name: ubuntu-cloud-keyring
            state: present

        - name: Install apt packages
          apt:
            upgrade: dist
            update_cache: yes
          become: True
  when: install_uca_repository == "yes"

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Copy chrony configuration
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf

- name: Start and enable chronyd service
  service:
    name: chronyd
    enabled: yes
    state: restarted

- name: Start and enable chrony service
  service:
    name: chrony
    enabled: yes
    state: restarted
